spring.application.name=liverpool

server.port=8080

spring.r2dbc.url=r2dbc:mysql://localhost:3306/dbojimmor?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.r2dbc.username=root
spring.r2dbc.password=root

# Permite que la base de datos se inicialice y cree tablas con el esquema al iniciar
spring.sql.init.mode=always

spring.jpa.show-sql=false

