/*
delete from ENT_USUARIOS
where NOMBRE in ('Ricardo','Ximena','Juan','Noria');

INSERT INTO ENT_USUARIOS (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, USER_NAME) 
VALUES('Ricardo','Jimenez','Moreno','jimmorjm1109@hotmail.com','jimmorjm');

INSERT INTO ENT_USUARIOS (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, USER_NAME) 
VALUES('Ximena','Lopez','Gomez','kxLg@gmail.com','xlopez');

INSERT INTO ENT_USUARIOS (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, USER_NAME) 
VALUES('Juan','Camacho','Rodriguez','ecamacho@gmail.com','ecamacho');

INSERT INTO ENT_USUARIOS (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, USER_NAME) 
VALUES('Noria','Medina','Medina','nmedina@gmail.com','nmedina');



INSERT INTO CAT_PRODUCTO(CLAVE,DESCRIPTION, COSTO_UNITARIO, INVENTARIO_DISPONIBLE, DISPLAY_NAME)
VALUES("PROD-1234", "Telefono Samsung Galaxi S21 FE", 2000.00, 15, "Samsun S21 FE");

INSERT INTO CAT_PRODUCTO(CLAVE,DESCRIPTION, COSTO_UNITARIO, INVENTARIO_DISPONIBLE, DISPLAY_NAME)
VALUES("PROD-2299", "SmartTv LG 85 Pulgadas full HD 4K", 15000.00, 20, "LG 85 4K");


INSERT INTO CAT_PRODUCTO(CLAVE,DESCRIPTION, COSTO_UNITARIO, INVENTARIO_DISPONIBLE, DISPLAY_NAME)
VALUES("PROD-9876", "LapTop Asus Gammer Rog icore7, GeforceGTX, 500G Solido, 16RAM", 34000.00, 20, "Asus Gammer ROG");
*/
