/*DROP TABLE IF EXISTS ENT_USUARIOS;
DROP TABLE IF EXISTS ENT_DETALLE_USUARIO;
DROP TABLE IF EXISTS ENT_PEDIDO;
DROP TABLE IF EXISTS ENT_PEDIDO_PRODUCTO;
DROP TABLE IF EXISTS CAT_PRODUCTO;
*/
CREATE TABLE IF NOT EXISTS ENT_USUARIOS (
    ID_USUARIO BIGINT  NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    APELLIDO_PATERNO VARCHAR(255),
    APELLIDO_MATERNO VARCHAR(255),
    CORREO VARCHAR(255),
    USER_NAME VARCHAR(255),
    PRIMARY KEY (ID_USUARIO) 
);

CREATE TABLE IF NOT EXISTS ENT_DETALLE_USUARIO (
    ID_DETALLE_USUARIO BIGINT  NOT NULL AUTO_INCREMENT,
    CALLE_NUMERO       VARCHAR(255),
    COLONIA_MUNICIPIO  VARCHAR(255),
    DEL_ALCALDIA       VARCHAR(255),
    CODIGO_POSTAL      VARCHAR(20),
    ESTADO             VARCHAR(100),
    ID_USUARIO         BIGINT ,
    ESTATUS_DETALLE_USUARIO BIGINT,
    PRIMARY KEY (ID_DETALLE_USUARIO)
);

CREATE TABLE IF NOT EXISTS ENT_PEDIDO (
    ID_PEDIDO BIGINT  NOT NULL AUTO_INCREMENT,
    CANAL_VENTA VARCHAR(255),
    ESTATUS_PEDIDO INT,
    TOTAL_PEDIDO DOUBLE,
    ID_DETALLE_USUARIO BIGINT ,
    PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE IF NOT EXISTS ENT_PEDIDO_PRODUCTO (
    ID_PEDIDO_PRODUCTO BIGINT  NOT NULL AUTO_INCREMENT,
    ID_PEDIDO BIGINT ,
    ID_PRODUCTO BIGINT ,
    CANTIDAD_PIEZAS INT,
    ESTATUS_PRODUCTO INT,
    PRIMARY KEY (ID_PEDIDO_PRODUCTO)
);

CREATE TABLE IF NOT EXISTS CAT_PRODUCTO (
    ID_PRODUCTO BIGINT  NOT NULL AUTO_INCREMENT,
    CLAVE VARCHAR(100),
    DESCRIPTION VARCHAR(255),
    COSTO_UNITARIO DOUBLE,
    INVENTARIO_DISPONIBLE INT,
    DISPLAY_NAME VARCHAR(255),
    PRIMARY KEY (ID_PRODUCTO)
);
